version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "ci/cd"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/whisper-post-processor"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "java"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    
  # Python dependencies (optional)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "python"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Only update if there are security updates
    open-pull-requests-limit: 2
    allow:
      - dependency-type: "direct"
    ignore:
      # Don't update Whisper too frequently as it might break compatibility
      - dependency-name: "openai-whisper"
        update-types: ["version-update:semver-patch"]