# Configuration for actions/labeler
# Automatically labels PRs based on files changed

java:
  - whisper-post-processor/**/*.java
  - whisper-post-processor/build.gradle

tests:
  - whisper-post-processor/src/test/**/*
  - scripts/testing/**/*
  - tests/**/*

documentation:
  - "**/*.md"
  - docs/**/*
  - examples/**/*

lua:
  - hammerspoon/**/*.lua

ci/cd:
  - .github/**/*
  - Makefile

dependencies:
  - requirements*.txt
  - Brewfile
  - "**/build.gradle"
  - "**/gradle.properties"

breaking-change:
  - hammerspoon/ptt_config.lua
  - hammerspoon/push_to_talk.lua

enhancement:
  - whisper-post-processor/src/main/java/com/cliffmin/whisper/processors/**/*